# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160801201541 on 2016-08-05 18:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('release_time', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('DUT_count', models.IntegerField()),
                ('num_testbenches', models.IntegerField()),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='AssignmentTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_order', models.IntegerField()),
                ('description', models.TextField()),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.Assignment')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='AssignmentTestBenches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.Assignment')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='DUT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dut_type', models.CharField(choices=[('mbed', 'mbed'), ('ice40', 'Lattice iCE40')], default='mbed', max_length=10)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='DUTToDUTWiring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DUT_first_pin', models.CharField(max_length=5)),
                ('DUT_second_pin', models.CharField(max_length=5)),
                ('DUT_first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DUT_first', to='serapis.DUT')),
                ('DUT_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DUT_second', to='serapis.DUT')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='HardwareTestBench',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('avail', 'Available')], default='avail', max_length=10)),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='HardwareTester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester_type', models.CharField(choices=[('beagle', 'BeagleBone'), ('rpi3', 'RaspberryPi3')], default='beagle', max_length=10)),
                ('firmware', models.FileField(upload_to='documents/tester_code/%Y/%m/%d')),
                ('testbench', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.HardwareTestBench')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_time', models.DateTimeField()),
                ('grading_result', models.FloatField()),
                ('status', models.IntegerField(choices=[(0, 'Received'), (10, 'Grading'), (11, 'Rejudging'), (20, 'Final result')], default=0)),
                ('assignment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.Assignment')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.Submission')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='TesterToDUTWiring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tester_pin', models.CharField(max_length=5)),
                ('dut_pin', models.CharField(max_length=5)),
                ('dut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.DUT')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.HardwareTester')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.IntegerField(choices=[(0, 'Super user'), (10, 'Instructor'), (11, 'TA'), (12, 'Grader'), (20, 'Student')], default=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.UserProfile'),
        ),
        migrations.AddField(
            model_name='dut',
            name='testbench',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.HardwareTestBench'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.UserProfile'),
        ),
        migrations.AddField(
            model_name='assignmenttestbenches',
            name='testbench_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.HardwareTestBench'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.Course'),
        ),
    ]
