# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-20 20:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from serapis.models import Assignment, Team, TeamMember, Submission
from serapis.utils.team_helper import create_team

def submission_data_migration(apps, schema_editor):
    # For each submission, create a new Team and TeamMember
    for submission in Submission.objects.all():
        try:
            team_member = TeamMember.objects.get(assignment_fk=submission.assignment_fk, user_fk=submission.student_fk)
            team = team_member.team_fk
        except:
            team, members = create_team(submission.assignment_fk, [submission.student_fk])
            team_member = members[0]

        submission.team_fk = team
        submission.save()
 
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serapis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passcode', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField()),
            ],
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='course_id',
            new_name='course_fk',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='testbed_type_id',
            new_name='testbed_type_fk',
        ),
        migrations.RenameField(
            model_name='assignmenttask',
            old_name='assignment_id',
            new_name='assignment_fk',
        ),
        migrations.RenameField(
            model_name='assignmenttaskfile',
            old_name='assignment_task_id',
            new_name='assignment_task_fk',
        ),
        migrations.RenameField(
            model_name='assignmenttaskfile',
            old_name='file_schema_id',
            new_name='file_schema_fk',
        ),
        migrations.RenameField(
            model_name='assignmenttaskfileschema',
            old_name='assignment_id',
            new_name='assignment_fk',
        ),
        migrations.RenameField(
            model_name='courseuserlist',
            old_name='course_id',
            new_name='course_fk',
        ),
        migrations.RenameField(
            model_name='courseuserlist',
            old_name='user_id',
            new_name='user_fk',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='assignment_id',
            new_name='assignment_fk',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='student_id',
            new_name='student_fk',
        ),
        migrations.RenameField(
            model_name='submissionfile',
            old_name='file_schema_id',
            new_name='file_schema_fk',
        ),
        migrations.RenameField(
            model_name='submissionfile',
            old_name='submission_id',
            new_name='submission_fk',
        ),
        migrations.RenameField(
            model_name='submissionfileschema',
            old_name='assignment_id',
            new_name='assignment_fk',
        ),
        migrations.RenameField(
            model_name='taskgradingstatus',
            old_name='assignment_task_id',
            new_name='assignment_task_fk',
        ),
        migrations.RenameField(
            model_name='taskgradingstatus',
            old_name='submission_id',
            new_name='submission_fk',
        ),
        migrations.RenameField(
            model_name='taskgradingstatusfile',
            old_name='file_schema_id',
            new_name='file_schema_fk',
        ),
        migrations.RenameField(
            model_name='taskgradingstatusfile',
            old_name='task_grading_status_id',
            new_name='task_grading_status_fk',
        ),
        migrations.RenameField(
            model_name='taskgradingstatusfileschema',
            old_name='assignment_id',
            new_name='assignment_fk',
        ),
        migrations.RenameField(
            model_name='testbed',
            old_name='testbed_type_id',
            new_name='testbed_type_fk',
        ),
        migrations.AddField(
            model_name='assignment',
            name='num_max_team_members',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='assignmenttaskfile',
            unique_together=set([('assignment_task_fk', 'file_schema_fk')]),
        ),
        migrations.AlterUniqueTogether(
            name='assignmenttaskfileschema',
            unique_together=set([('assignment_fk', 'field')]),
        ),
        migrations.AlterUniqueTogether(
            name='courseuserlist',
            unique_together=set([('course_fk', 'user_fk')]),
        ),
        migrations.AlterUniqueTogether(
            name='submissionfile',
            unique_together=set([('submission_fk', 'file_schema_fk')]),
        ),
        migrations.AlterUniqueTogether(
            name='submissionfileschema',
            unique_together=set([('assignment_fk', 'field')]),
        ),
        migrations.AlterUniqueTogether(
            name='taskgradingstatus',
            unique_together=set([('submission_fk', 'assignment_task_fk')]),
        ),
        migrations.AlterUniqueTogether(
            name='taskgradingstatusfile',
            unique_together=set([('task_grading_status_fk', 'file_schema_fk')]),
        ),
        migrations.AlterUniqueTogether(
            name='taskgradingstatusfileschema',
            unique_together=set([('assignment_fk', 'field')]),
        ),
        migrations.AddField(
            model_name='teammember',
            name='assignment_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.Assignment'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='team_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.Team'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='assignment_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.Assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='team_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serapis.Team'),
        ),
        migrations.RunPython(submission_data_migration),
        migrations.AlterField(
            model_name='submission',
            name='team_fk',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='serapis.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together=set([('assignment_fk', 'user_fk')]),
        ),
    ]
