# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160801201541 on 2016-08-17 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
