# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160819220457 on 2016-08-19 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0002_auto_20160817_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default='A123456789', max_length=20, unique=True, verbose_name='University ID'),
        ),
    ]
