# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160801201541 on 2017-09-24 21:16
from __future__ import unicode_literals

from django.db import migrations, models

from serapis.models import Submission, TaskGradingStatus


def submission_data_migration(apps, schema_editor):
    # Sync the value with TaskGradingStatus
    for submission in Submission.objects.all():
        grading_list = TaskGradingStatus.objects.filter(submission_fk=submission)
        submission.num_total_tasks = len(grading_list)
        submission.num_graded_tasks = sum([t.is_grading_done() for t in grading_list])
        submission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0002_aad7fd5'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='num_graded_tasks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='num_total_tasks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.RunPython(submission_data_migration),
    ]
