# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160801201541 on 2016-08-23 20:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0003_userprofile_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='DUT_count',
        ),
        migrations.RemoveField(
            model_name='dut',
            name='testbench',
        ),
        migrations.RemoveField(
            model_name='hardwaretester',
            name='testbench',
        ),
        migrations.AddField(
            model_name='assignment',
            name='input_statement',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='output_statement',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='problem_statement',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='testbench_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serapis.HardwareTestBench'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardwaretestbench',
            name='DUT1_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='DUT1_type', to='serapis.DUT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardwaretestbench',
            name='DUT2_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='DUT2_type', to='serapis.DUT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardwaretestbench',
            name='DUT_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hardwaretestbench',
            name='tester_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='serapis.HardwareTester'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='uid',
            field=models.CharField(default='123456789', max_length=20, unique=True, verbose_name='University ID'),
        ),
    ]
