# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160801201541 on 2017-11-02 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0003_auto_20170924_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='num_max_team_members',
            new_name='max_num_team_members',
        ),
    ]
