# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160801201541 on 2016-08-23 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0004_auto_20160823_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='num_testbenches',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='testbench_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='serapis.HardwareTestBench'),
        ),
    ]
