# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160801201541 on 2017-11-02 20:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models

from serapis.models import Assignment

class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0004_auto_20171102_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_num_submissions',
            field=models.IntegerField(default=Assignment.SUBMISSION_LIMIT_INFINITE, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
