# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160801201541 on 2016-08-24 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0005_auto_20160823_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardwareDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='HardwareType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pinout', models.FileField(upload_to='')),
                ('link_to_manual', models.URLField()),
                ('hardware_role', models.IntegerField(choices=[(0, 'Hardware Engine'), (1, 'Device Under Test')])),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='HardwareTypePin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_name', models.CharField(max_length=10)),
                ('hardware_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.HardwareType')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Testbed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('avail', 'Available')], default='avail', max_length=10)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='TestbedHardwareList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware_index', models.IntegerField()),
                ('firmware', models.FileField(blank=True, null=True, upload_to='')),
                ('hardware_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.HardwareType')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='TestbedType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='TestbedTypeWiring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_1_index', models.IntegerField()),
                ('dev_2_index', models.IntegerField()),
                ('dev_1_pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_1_pin', to='serapis.HardwareTypePin')),
                ('dev_2_pin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dev_2_pin', to='serapis.HardwareTypePin')),
                ('testbed_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.TestbedType')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.RenameModel(
            old_name='AssignmentTestBenches',
            new_name='AssignmentTestbed',
        ),
        migrations.RemoveField(
            model_name='duttodutwiring',
            name='DUT_first',
        ),
        migrations.RemoveField(
            model_name='duttodutwiring',
            name='DUT_second',
        ),
        migrations.RemoveField(
            model_name='hardwaretestbench',
            name='DUT1_type',
        ),
        migrations.RemoveField(
            model_name='hardwaretestbench',
            name='DUT2_type',
        ),
        migrations.RemoveField(
            model_name='hardwaretestbench',
            name='tester_type',
        ),
        migrations.RemoveField(
            model_name='testertodutwiring',
            name='dut',
        ),
        migrations.RemoveField(
            model_name='testertodutwiring',
            name='tester',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='num_testbenches',
            new_name='num_testbeds',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='testbench_id',
        ),
        migrations.RemoveField(
            model_name='assignmenttestbed',
            name='testbench_id',
        ),
        migrations.DeleteModel(
            name='DUT',
        ),
        migrations.DeleteModel(
            name='DUTToDUTWiring',
        ),
        migrations.DeleteModel(
            name='HardwareTestBench',
        ),
        migrations.DeleteModel(
            name='HardwareTester',
        ),
        migrations.DeleteModel(
            name='TesterToDUTWiring',
        ),
        migrations.AddField(
            model_name='testbed',
            name='testbed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.TestbedType'),
        ),
        migrations.AddField(
            model_name='hardwaredevice',
            name='hardware_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.HardwareType'),
        ),
        migrations.AddField(
            model_name='hardwaredevice',
            name='testbed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.Testbed'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='testbed_type_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='serapis.TestbedType'),
        ),
        migrations.AddField(
            model_name='assignmenttestbed',
            name='testbed_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='serapis.Testbed'),
            preserve_default=False,
        ),
    ]
