# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160801201541 on 2016-08-26 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0007_auto_20160824_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quarter',
            field=models.IntegerField(choices=[(0, 'Fall'), (1, 'Winter'), (2, 'Spring'), (3, 'Summer')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], default=2016),
        ),
        migrations.AlterField(
            model_name='hardwaretype',
            name='pinout',
            field=models.FileField(upload_to='uploaded_files'),
        ),
    ]
