# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160801201541 on 2016-08-26 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0008_auto_20160826_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='quarter',
            field=models.IntegerField(choices=[(0, 'Fall'), (1, 'Winter'), (2, 'Spring'), (3, 'Summer')], default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(2015, 2015), (2016, 2016), (2017, 2017)], default=2016),
        ),
    ]
