# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160801201541 on 2016-08-27 01:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serapis', '0010_auto_20160826_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseUserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='instructor_id',
        ),
        migrations.AddField(
            model_name='course',
            name='owner_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseuserlist',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.Course'),
        ),
        migrations.AddField(
            model_name='courseuserlist',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
