# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160801201541 on 2016-08-29 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0012_testbedhardwarelist_testbed_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmenttask',
            name='description',
        ),
        migrations.RemoveField(
            model_name='assignmenttask',
            name='task_order',
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='brief_description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
