# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160801201541 on 2016-08-30 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0013_auto_20160828_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttask',
            name='grading_script',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='mode',
            field=models.IntegerField(choices=[(0, 'Public'), (1, 'Feedback'), (2, 'Hidden')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='points',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmenttask',
            name='test_input',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
