# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160819220457 on 2016-09-01 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0015_auto_20160831_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskGradingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Received'), (10, 'Grading'), (100, 'Segmentation fault')], default=0)),
                ('points', models.FloatField(default=0.0)),
                ('assignment_task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.AssignmentTask')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.IntegerField(choices=[(0, 'Received'), (10, 'Grading'), (11, 'Rejudging'), (20, 'Result is ready')], default=0),
        ),
        migrations.AddField(
            model_name='taskgradingstatus',
            name='submission_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.Submission'),
        ),
    ]
