# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160819220457 on 2016-09-01 01:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0016_auto_20160831_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploaded_files')),
                ('submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serapis.Submission')),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
