# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160819220457 on 2016-09-01 07:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0017_submissionfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
