# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160819220457 on 2016-09-02 03:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0018_auto_20160901_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='description',
        ),
        migrations.RemoveField(
            model_name='taskgradingstatus',
            name='status',
        ),
        migrations.AddField(
            model_name='taskgradingstatus',
            name='execution_status',
            field=models.IntegerField(choices=[(-1, "Haven't executed yet"), (0, 'Successful execution'), (1, 'Segmentation fault')], default=-1),
        ),
        migrations.AddField(
            model_name='taskgradingstatus',
            name='grading_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (10, 'Executing'), (100, 'Checking output'), (110, 'Finished')], default=0),
        ),
        migrations.AddField(
            model_name='taskgradingstatus',
            name='status_update_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 1, 20, 39, 0, 392993)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testbed',
            name='report_status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Busy'), (-2, 'Unknown')], default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testbed',
            name='report_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 1, 20, 39, 45, 25107)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testbed',
            name='status',
            field=models.IntegerField(choices=[(1, 'Available'), (2, 'Busy'), (-1, 'Offline')]),
        ),
    ]
