# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160819220457 on 2016-09-02 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0019_auto_20160901_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='testbed',
            name='unique_hardware_id',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskgradingstatus',
            name='execution_status',
            field=models.IntegerField(choices=[(-1, "Haven't executed yet"), (0, 'Successful execution'), (1, 'Segmentation fault')], default=((-1, "Haven't executed yet"), (0, 'Successful execution'), (1, 'Segmentation fault'))),
        ),
    ]
