# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160819220457 on 2016-09-03 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0020_auto_20160902_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskgradingstatus',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files'),
        ),
    ]
