# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160819220457 on 2016-09-07 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0022_auto_20160906_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmenttestbed',
            name='assignment_id',
        ),
        migrations.RemoveField(
            model_name='assignmenttestbed',
            name='testbed_id',
        ),
        migrations.AddField(
            model_name='testbed',
            name='task_being_graded',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='serapis.TaskGradingStatus'),
        ),
        migrations.DeleteModel(
            name='AssignmentTestbed',
        ),
    ]
