# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160819220457 on 2016-09-22 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0024_auto_20160922_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseuserlist',
            name='role',
            field=models.IntegerField(choices=[(0, 'Super user'), (10, 'Instructor'), (11, 'TA'), (12, 'Grader'), (20, 'Student')], default=20),
        ),
    ]
