# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160922233719 on 2016-10-03 05:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0025_courseuserlist_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='owner_id',
        ),
    ]
