# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160922233719 on 2016-10-03 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serapis', '0026_remove_course_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttask',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
